#!/bin/sh

#
# Build a root certificate
#

SCR_NAME=`basename $0`
FULLPATH=`readlink -f $0`
SSL_DIR=`echo $FULLPATH | sed "s/\/common\/$SCR_NAME//g"`
KEY_CONFIG=$SSL_DIR/openssl.cnf
KEY_DIR=$SSL_DIR/certs

if [ -f $SSL_DIR/cacert.pem ]
then
  echo "CA Zertifikat existiert bereits. Breche ab"
  echo "Verzeichnis muss evtl. neu initialisiert werden"
  exit 0
fi

export KEY_COMMON="Certification Authority"
export SSL_DIR
. $SSL_DIR/common/config


if test $KEY_DIR; then
        cd $KEY_DIR && \
        openssl req -sha256 -batch -days 3660 -nodes -new -x509 -keyout ca.key -out ca.crt -days 3660 -config $KEY_CONFIG && \
        chmod 0600 ca.key
        cp $KEY_DIR/ca.crt $SSL_DIR/cacert.pem
        cp $KEY_DIR/ca.key $SSL_DIR/private/cakey.pem
else
        echo you must define KEY_DIR
fi

